export enum TicketType {
    STANDARD_2D = 'STANDARD_2D',
    STANDARD_3D = 'STANDARD_3D',
    VIP_2D = 'VIP_2D',
    VIP_3D = 'VIP_3D',
    ONE_DAY_PASS = 'ONE_DAY_PASS',
    TWO_DAY_PASS = 'TWO_DAY_PASS',
    THREE_DAY_PASS = 'THREE_DAY_PASS'
}
